version: '3'

services:
  redis-master:
    image: redis:7-alpine
    container_name: redis-master
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD} --masterauth ${REDIS_PASSWORD}
    volumes:
      - "./data/master:/data"
    ports:
      - "${REDIS_MASTER_PORT}:${REDIS_MASTER_PORT}"
    networks:
      - ${DOCKER_NETWORK_NAME}
 