version: '3'

services:
  redis-master:
    image: redis:7-alpine
    container_name: redis-master
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD} --masterauth ${REDIS_PASSWORD}
    volumes:
      - "./data/master:/data"
    ports:
      - "${REDIS_MASTER_PORT}:${REDIS_MASTER_PORT}"
    networks:
      - ${DOCKER_NETWORK_NAME}
 
  redis-slave:
    image: redis:7-alpine
    container_name: redis-slave
    restart: always
    command: redis-server --slaveof ${REDIS_MASTER_HOST} ${REDIS_MASTER_PORT} --port ${REDIS_SLAVE_PORT} --masterauth ${REDIS_PASSWORD} --requirepass ${REDIS_PASSWORD}
    volumes:
      - "./data/slave:/data"
    ports:
      - "${REDIS_SLAVE_PORT}:${REDIS_SLAVE_PORT}"
    networks:
      - ${DOCKER_NETWORK_NAME}
     
  # Sentinel instance 1
  redis-sentinel-1:
    container_name: redis-sentinel-1
    restart: always
    build: 
      context: ./redis-sentinel-base
      args:
        - REDIS_MASTER_HOST=${REDIS_MASTER_HOST}
        - REDIS_MASTER_PORT=${REDIS_MASTER_PORT}
        - REDIS_PASSWORD=${REDIS_PASSWORD}
        - REDIS_SENTINEL_NAME=${REDIS_SENTINEL_NAME}
        - REDIS_SENTINEL_PORT=${REDIS_SENTINEL1_PORT}
        - REDIS_SENTINEL_QUORUM=${REDIS_SENTINEL_QUORUM}
        - REDIS_SENTINEL_DOWN_AFTER=${REDIS_SENTINEL_DOWN_AFTER}
        - REDIS_SENTINEL_FAILOVER=${REDIS_SENTINEL_FAILOVER}
    ports:
      - "${REDIS_SENTINEL1_PORT}:${REDIS_SENTINEL1_PORT}"
    networks:
      - ${DOCKER_NETWORK_NAME}
 
  # Sentinel instance 2
  redis-sentinel-2:
    container_name: redis-sentinel-2
    restart: always
    build: 
      context: ./redis-sentinel-base
      args:
        - REDIS_MASTER_HOST=${REDIS_MASTER_HOST}
        - REDIS_MASTER_PORT=${REDIS_MASTER_PORT}
        - REDIS_PASSWORD=${REDIS_PASSWORD}
        - REDIS_SENTINEL_NAME=${REDIS_SENTINEL_NAME}
        - REDIS_SENTINEL_PORT=${REDIS_SENTINEL2_PORT}
        - REDIS_SENTINEL_QUORUM=${REDIS_SENTINEL_QUORUM}
        - REDIS_SENTINEL_DOWN_AFTER=${REDIS_SENTINEL_DOWN_AFTER}
        - REDIS_SENTINEL_FAILOVER=${REDIS_SENTINEL_FAILOVER}
    ports:
      - "${REDIS_SENTINEL2_PORT}:${REDIS_SENTINEL2_PORT}"
    networks:
      - ${DOCKER_NETWORK_NAME}
  
  # Sentinel instance 3
  redis-sentinel-3:
    container_name: redis-sentinel-3
    restart: always
    build: 
      context: ./redis-sentinel-base
      args:
        - REDIS_MASTER_HOST=${REDIS_MASTER_HOST}
        - REDIS_MASTER_PORT=${REDIS_MASTER_PORT}
        - REDIS_PASSWORD=${REDIS_PASSWORD}
        - REDIS_SENTINEL_NAME=${REDIS_SENTINEL_NAME}
        - REDIS_SENTINEL_PORT=${REDIS_SENTINEL3_PORT}
        - REDIS_SENTINEL_QUORUM=${REDIS_SENTINEL_QUORUM}
        - REDIS_SENTINEL_DOWN_AFTER=${REDIS_SENTINEL_DOWN_AFTER}
        - REDIS_SENTINEL_FAILOVER=${REDIS_SENTINEL_FAILOVER}
    ports:
      - "${REDIS_SENTINEL3_PORT}:${REDIS_SENTINEL3_PORT}"
    networks:
      - ${DOCKER_NETWORK_NAME}
