version: '3'

services:
  # Sentinel instance 3
  redis-sentinel-3:
    container_name: redis-sentinel-3
    restart: always
    build: 
      context: ./redis-sentinel-base
      args:
        - REDIS_MASTER_HOST=${REDIS_MASTER_HOST}
        - REDIS_MASTER_PORT=${REDIS_MASTER_PORT}
        - REDIS_PASSWORD=${REDIS_PASSWORD}
        - REDIS_SENTINEL_NAME=${REDIS_SENTINEL_NAME}
        - REDIS_SENTINEL_PORT=${REDIS_SENTINEL3_PORT}
        - REDIS_SENTINEL_QUORUM=${REDIS_SENTINEL_QUORUM}
        - REDIS_SENTINEL_DOWN_AFTER=${REDIS_SENTINEL_DOWN_AFTER}
        - REDIS_SENTINEL_FAILOVER=${REDIS_SENTINEL_FAILOVER}
    ports:
      - "${REDIS_SENTINEL3_PORT}:${REDIS_SENTINEL3_PORT}"
    networks:
      - ${DOCKER_NETWORK_NAME}
