version: '3'

services:
  # Sentinel instance 2
  redis-sentinel-2:
    container_name: redis-sentinel-2
    restart: always
    build: 
      context: ./redis-sentinel-base
      args:
        - REDIS_MASTER_HOST=${REDIS_MASTER_HOST}
        - REDIS_MASTER_PORT=${REDIS_MASTER_PORT}
        - REDIS_PASSWORD=${REDIS_PASSWORD}
        - REDIS_SENTINEL_NAME=${REDIS_SENTINEL_NAME}
        - REDIS_SENTINEL_PORT=${REDIS_SENTINEL2_PORT}
        - REDIS_SENTINEL_QUORUM=${REDIS_SENTINEL_QUORUM}
        - REDIS_SENTINEL_DOWN_AFTER=${REDIS_SENTINEL_DOWN_AFTER}
        - REDIS_SENTINEL_FAILOVER=${REDIS_SENTINEL_FAILOVER}
    ports:
      - "${REDIS_SENTINEL2_PORT}:${REDIS_SENTINEL2_PORT}"
    networks:
      - ${DOCKER_NETWORK_NAME}
