version: '3'

services:
  redis-slave:
    image: redis:7-alpine
    container_name: redis-slave
    restart: always
    command: redis-server --slaveof ${REDIS_MASTER_HOST} ${REDIS_MASTER_PORT} --port ${REDIS_SLAVE_PORT} --masterauth ${REDIS_PASSWORD} --requirepass ${REDIS_PASSWORD}
    volumes:
      - "./data/slave:/data"
    ports:
      - "${REDIS_SLAVE_PORT}:${REDIS_SLAVE_PORT}"
    networks:
      - ${DOCKER_NETWORK_NAME}